platform :ios,'9.1'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'BlocksKit'
pod 'MBProgressHUD'
pod 'SVPullToRefresh'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'Masonry'
pod 'MD5Digest'
pod 'SDCycleScrollView'
